# Model Training and Evaluation

This notebook trains and evaluates multiple classification models for predicting customer churn.

Models:
- Logistic Regression
- K-Nearest Neighbors (KNN)
- Decision Tree
- Random Forest
- Gradient Boosting

Evaluation Metrics:
- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

In [1]:
import pandas as pd 
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from xgboost import XGBClassifier

In [2]:
# Load data

df = pd.read_csv("../data/Telco-Customer-Churn.csv")

In [3]:
# convert TotalCharges and drop the null val

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df = df.dropna()

In [4]:
# drop customer id
df = df.drop("customerID", axis=1)

In [5]:
# create features and target
X = df.drop("Churn", axis=1)
y = df["Churn"].map({"Yes":1, "No":0})

In [6]:
# One-hot encoding

X = pd.get_dummies(X, drop_first=True)

In [7]:
# split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [8]:
# scaling

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## model 1: Logistic Regression

In [9]:
lr = LogisticRegression(random_state=42,
    class_weight="balanced")

lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

In [10]:
acc_lr = accuracy_score(y_test, y_pred_lr)
prec_lr = precision_score(y_test, y_pred_lr)
rec_lr = recall_score(y_test,y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
roc_lr = roc_auc_score(y_test, y_pred_lr)

print("Accuracy : ", acc_lr)
print("precision : ", prec_lr )
print("Recall : ", rec_lr )
print("F1_score : ", f1_lr)
print("ROC-AUC", roc_lr)

Accuracy :  0.7263681592039801
precision :  0.49093904448105435
Recall :  0.7967914438502673
F1_score :  0.6075433231396534
ROC-AUC 0.7488313463200998

## model 2: K-Nearest Neighbors (KNN)

In [11]:
knn = KNeighborsClassifier()

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

In [12]:
acc_knn = accuracy_score(y_test, y_pred_knn)
prec_knn = precision_score(y_test, y_pred_knn)
rec_knn = recall_score(y_test,y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)
roc_knn = roc_auc_score(y_test, y_pred_knn)

print("Accuracy : ", acc_knn)
print("precision : ", prec_knn )
print("Recall : ", rec_knn )
print("F1_score : ", f1_knn)
print("ROC-AUC", roc_knn)

Accuracy :  0.7533759772565742
precision :  0.5361930294906166
Recall :  0.5347593582887701
F1_score :  0.535475234270415
ROC-AUC 0.6836429898897867

## Model 3: Decision Tree

In [13]:
dt = DecisionTreeClassifier(random_state=42, max_depth=5)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

In [14]:
acc_dt = accuracy_score(y_test, y_pred_dt)
prec_dt = precision_score(y_test, y_pred_dt)
rec_dt = recall_score(y_test,y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
roc_dt = roc_auc_score(y_test, y_pred_dt)

print("Accuracy : ", acc_dt)
print("precision : ", prec_dt )
print("Recall : ", rec_dt )
print("F1_score : ", f1_dt)
print("ROC-AUC", roc_dt)

Accuracy :  0.7782515991471215
precision :  0.5807291666666666
Recall :  0.5962566844919787
F1_score :  0.5883905013192612
ROC-AUC 0.720199978257606

## Model 4: Random Forest

In [15]:
rf = RandomForestClassifier(random_state=42, n_estimators=100)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

In [16]:
acc_rf = accuracy_score(y_test, y_pred_rf)
prec_rf = precision_score(y_test, y_pred_rf)
rec_rf = recall_score(y_test,y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
roc_rf = roc_auc_score(y_test, y_pred_rf)

print("Accuracy : ", acc_rf)
print("precision : ", prec_rf )
print("Recall : ", rec_rf )
print("F1_score : ", f1_rf)
print("ROC-AUC", roc_rf)

Accuracy :  0.7896233120113717
precision :  0.6258064516129033
Recall :  0.5187165775401069
F1_score :  0.5672514619883041
ROC-AUC 0.703211144529976

## Model 5: Gradient Boosting

In [17]:
gb = GradientBoostingClassifier(random_state=42, n_estimators=100, learning_rate=0.1)

gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

In [18]:
acc_gb = accuracy_score(y_test, y_pred_gb)
prec_gb = precision_score(y_test, y_pred_gb)
rec_gb = recall_score(y_test,y_pred_gb)
f1_gb = f1_score(y_test, y_pred_gb)
roc_gb = roc_auc_score(y_test, y_pred_gb)

print("Accuracy : ", acc_gb)
print("precision : ", prec_gb )
print("Recall : ", rec_gb )
print("F1_score : ", f1_gb)
print("ROC-AUC", roc_gb)

Accuracy :  0.7953091684434968
precision :  0.6378205128205128
Recall :  0.5320855614973262
F1_score :  0.5801749271137027
ROC-AUC 0.7113477178251395

In [19]:
results = pd.DataFrame({

    "Model":[
        "Logistic Regression",
        "KNN",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy": [
        acc_lr,
        acc_knn,
        acc_dt,
        acc_rf,
        acc_gb

    ],
        "precision": [
        prec_lr,
        prec_knn,
        prec_dt,
        prec_rf,
        prec_gb

    ],  
      
        "Recall": [
       rec_lr,
       rec_knn,
       rec_dt,
       rec_rf,
       rec_gb

    ],  
      
        "F1_score": [
        f1_lr,
        f1_knn,
        f1_dt,
        f1_rf,
        f1_gb

    ],  
      
        "ROC-AUC": [
        roc_lr,
        roc_knn,
        roc_dt,
        roc_rf,
        roc_gb

    ]
})

results.sort_values(by="F1_score", ascending=False)

                 Model  Accuracy  precision    Recall  F1_score   ROC-AUC
0  Logistic Regression  0.726368   0.490939  0.796791  0.607543  0.748831
2        Decision Tree  0.778252   0.580729  0.596257  0.588391  0.720200
4    Gradient Boosting  0.795309   0.637821  0.532086  0.580175  0.711348
3        Random Forest  0.789623   0.625806  0.518717  0.567251  0.703211
1                  KNN  0.753376   0.536193  0.534759  0.535475  0.683643

In [20]:
confusion_matrix(y_test, y_pred_lr)

array([[724, 309],
       [ 76, 298]])

In [21]:
model_columns = joblib.load("../models/model_columns.pkl")

feature_importance = pd.DataFrame({
    "feature": model_columns,
    "coef": lr.coef_[0]
}).sort_values(by="coef", ascending=False)

In [22]:
feature_importance = pd.DataFrame({
    "feature": model_columns,
    "coef": lr.coef_[0]
}).sort_values(by="coef", ascending=False)

feature_importance

                                  feature      coef
10            InternetService_Fiber optic  0.746144
3                            TotalCharges  0.623279
21                        StreamingTV_Yes  0.259691
23                    StreamingMovies_Yes  0.252870
9                       MultipleLines_Yes  0.202763
28         PaymentMethod_Electronic check  0.193697
26                   PaperlessBilling_Yes  0.124250
0                           SeniorCitizen  0.075306
17                   DeviceProtection_Yes  0.069476
27  PaymentMethod_Credit card (automatic)  0.029226
29             PaymentMethod_Mailed check  0.023623
8          MultipleLines_No phone service  0.001330
7                        PhoneService_Yes -0.001330
4                             gender_Male -0.005694
15                       OnlineBackup_Yes -0.017882
5                             Partner_Yes -0.020069
14       OnlineBackup_No internet service -0.091307
20        StreamingTV_No internet service -0.091307
11                     InternetService_No -0.091307
12     OnlineSecurity_No internet service -0.091307
18        TechSupport_No internet service -0.091307
16   DeviceProtection_No internet service -0.091307
22    StreamingMovies_No internet service -0.091307
6                          Dependents_Yes -0.103848
19                        TechSupport_Yes -0.105289
13                     OnlineSecurity_Yes -0.124312
24                      Contract_One year -0.326693
25                      Contract_Two year -0.638598
2                          MonthlyCharges -0.928682
1                                  tenure -1.263854

In [23]:
xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [24]:
y_pred_xgb = xgb.predict(X_test)
y_prob_xgb = xgb.predict_proba(X_test)[:,1]

In [25]:
acc_xgb = accuracy_score(y_test, y_pred_xgb)
prec_xgb = precision_score(y_test,y_pred_xgb)
rec_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)
roc_xgb = roc_auc_score(y_test, y_pred_xgb)

print("Accuracy: ", acc_xgb)
print("Precision: ", prec_xgb)
print("Recall: ", rec_xgb)
print("F1: ", f1_xgb)
print("ROC-AUC: ", roc_xgb)

Accuracy:  0.7839374555792467
Precision:  0.610062893081761
Recall:  0.5187165775401069
F1:  0.5606936416184971
ROC-AUC:  0.6993389276858327

In [26]:
threshold = 0.35
y_pred_thresh = (y_prob_xgb >= threshold).astype(int)
classificationReport = classification_report(y_test, y_pred_thresh)
print(classificationReport)

              precision    recall  f1-score   support

           0       0.89      0.78      0.83      1033
           1       0.55      0.73      0.63       374

    accuracy                           0.77      1407
   macro avg       0.72      0.76      0.73      1407
weighted avg       0.80      0.77      0.78      1407

In [27]:
confusion_matrix(y_test, y_pred_xgb)

array([[909, 124],
       [180, 194]])

In [28]:
y_pred_xgb = (y_prob_xgb >= 0.30).astype(int)

In [29]:
confusion_matrix(y_test, y_pred_xgb)

array([[764, 269],
       [ 87, 287]])

In [30]:
joblib.dump(xgb, "../models/churn_model.pkl")
joblib.dump(scaler, "../models/scaler.pkl")
joblib.dump(X.columns.tolist(), "../models/model_columns.pkl")

['../models/model_columns.pkl']